version: "3.7"
name: comexp

services:
  processor:
    image: comexp-image
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A main worker -B"
    volumes:
      - ./:/app
    networks:
      - docker_net

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - docker_net


networks:
  docker_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.name: "docker_net"

